import { StyleSheet } from "react-native";

export const colors = {
  bg: "#f5f8f8",
  card: "#ffffff",
  ink: "#172125",
  muted: "#6f7f84",
  teal: "#006878",
  tealDark: "#005a67",
  tealSoft: "#dff5f2",
  line: "#edf1f2",
  green: "#8ef2a8",
  greenText: "#007a45",
  red: "#ffd8d8",
  redText: "#b82025",
  amber: "#ffd9aa",
  pale: "#eef2f3",
};

export const shadow = {
  shadowColor: "#0b3440",
  shadowOpacity: 0.08,
  shadowRadius: 18,
  shadowOffset: { width: 0, height: 10 },
  elevation: 4,
};

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  phone: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  header: {
    height: 76,
    paddingHorizontal: 25,
    paddingTop: 11,
    flexDirection: "row",
    alignItems: "center",
  },
  iconButton: {
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  brand: {
    marginLeft: 10,
    fontSize: 19,
    lineHeight: 23,
    fontWeight: "800",
    color: "#00485a",
  },
  headerSpacer: {
    flex: 1,
  },
  adminAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: colors.teal,
  },
  sidebarOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 30,
    elevation: 30,
  },
  sidebarBackdrop: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: "rgba(8, 25, 31, 0.32)",
  },
  sidebarPanel: {
    width: "78%",
    maxWidth: 310,
    height: "100%",
    backgroundColor: "#ffffff",
    paddingHorizontal: 18,
    paddingTop: 42,
    paddingBottom: 24,
    shadowColor: "#062a34",
    shadowOpacity: 0.18,
    shadowRadius: 22,
    shadowOffset: { width: 7, height: 0 },
    elevation: 12,
  },
  sidebarTop: {
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  sidebarEyebrow: {
    color: "#536367",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.8,
  },
  sidebarClose: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#eef2f3",
    alignItems: "center",
    justifyContent: "center",
  },
  sidebarHomeButton: {
    height: 48,
    borderRadius: 12,
    backgroundColor: colors.teal,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    marginBottom: 18,
  },
  sidebarHomeText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "900",
  },
  sidebarSection: {
    borderTopWidth: 1,
    borderTopColor: colors.line,
    paddingTop: 12,
    marginTop: 6,
    gap: 8,
  },
  sidebarItem: {
    minHeight: 68,
    borderRadius: 13,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f5f8f8",
  },
  sidebarItemActive: {
    backgroundColor: colors.tealSoft,
  },
  sidebarItemIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#e7eef0",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 11,
  },
  sidebarItemIconActive: {
    backgroundColor: colors.teal,
  },
  sidebarItemCopy: {
    flex: 1,
    minWidth: 0,
  },
  sidebarItemTitle: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: "900",
  },
  sidebarItemDetail: {
    color: "#65757a",
    fontSize: 10,
    marginTop: 3,
  },
  sidebarStaticItem: {
    height: 43,
    borderRadius: 11,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  sidebarStaticText: {
    color: "#33464c",
    fontSize: 13,
    fontWeight: "800",
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 28,
    paddingBottom: 28,
  },
  dateText: {
    color: "#536367",
    fontSize: 14,
    marginTop: 2,
    marginBottom: 3,
  },
  pageTitle: {
    color: colors.ink,
    fontSize: 23,
    lineHeight: 29,
    fontWeight: "900",
    marginBottom: 28,
  },
  bigMetricCard: {
    minHeight: 151,
    backgroundColor: colors.card,
    borderRadius: 14,
    paddingHorizontal: 22,
    paddingVertical: 27,
    ...shadow,
  },
  metricLabel: {
    color: "#4e5e63",
    fontSize: 13,
    marginTop: 14,
  },
  metricValue: {
    color: colors.ink,
    fontSize: 30,
    fontWeight: "900",
    marginTop: 2,
  },
  growthText: {
    color: colors.greenText,
    fontSize: 12,
    fontWeight: "900",
    marginTop: 8,
  },
  metricGrid: {
    flexDirection: "row",
    gap: 16,
    marginTop: 16,
  },
  smallMetricCard: {
    flex: 1,
    minHeight: 111,
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: 17,
    ...shadow,
  },
  pendingCard: {
    backgroundColor: colors.amber,
  },
  smallMetricValue: {
    color: colors.ink,
    fontSize: 21,
    fontWeight: "900",
    marginTop: 3,
  },
  sectionHeadingRow: {
    marginTop: 30,
    marginBottom: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionTitle: {
    color: colors.ink,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: "900",
  },
  periodChip: {
    height: 24,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: "#e9eef0",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  periodText: {
    color: "#4c5b60",
    fontSize: 11,
    fontWeight: "700",
  },
  revenueCard: {
    height: 178,
    borderRadius: 13,
    backgroundColor: colors.teal,
    paddingHorizontal: 24,
    paddingTop: 23,
    overflow: "hidden",
  },
  revenueLabel: {
    color: "#a4d5db",
    fontSize: 12,
    marginBottom: 3,
  },
  revenueValue: {
    color: "#ffffff",
    fontSize: 26,
    fontWeight: "900",
  },
  chart: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 9,
    paddingTop: 12,
    paddingBottom: 18,
  },
  chartBar: {
    flex: 1,
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
    backgroundColor: "#ffffff",
  },
  queueTitle: {
    marginTop: 30,
    marginBottom: 14,
  },
  queueItem: {
    minHeight: 72,
    borderRadius: 13,
    backgroundColor: "#f0f3f4",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 18,
    marginBottom: 12,
  },
  queueAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  queueText: {
    flex: 1,
    marginLeft: 14,
  },
  queueName: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: "900",
  },
  queueDetail: {
    color: "#69777b",
    fontSize: 11,
    marginTop: 2,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 2,
  },
  searchBox: {
    flex: 1,
    height: 57,
    borderRadius: 13,
    backgroundColor: "#e8edef",
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
  },
  searchInput: {
    flex: 1,
    color: colors.ink,
    fontSize: 13,
    marginLeft: 14,
  },
  filterButton: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: "#dfe7e9",
    alignItems: "center",
    justifyContent: "center",
  },
  filterPills: {
    gap: 9,
    paddingVertical: 14,
  },
  filterPill: {
    height: 29,
    borderRadius: 14,
    paddingHorizontal: 17,
    backgroundColor: "#edf1f2",
    alignItems: "center",
    justifyContent: "center",
  },
  filterPillActive: {
    backgroundColor: colors.teal,
  },
  filterPillLive: {
    backgroundColor: colors.green,
  },
  filterPillFlagged: {
    backgroundColor: colors.red,
  },
  filterPillText: {
    color: "#5a676b",
    fontSize: 12,
    fontWeight: "900",
  },
  filterPillTextActive: {
    color: "#fff",
  },
  filterPillTextLive: {
    color: colors.greenText,
  },
  filterPillTextFlagged: {
    color: colors.redText,
  },
  listingCard: {
    backgroundColor: colors.card,
    borderRadius: 11,
    padding: 15,
    marginBottom: 18,
    ...shadow,
  },
  listingTop: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  listingImage: {
    width: 76,
    height: 76,
    borderRadius: 7,
    backgroundColor: colors.pale,
  },
  listingBody: {
    flex: 1,
    minWidth: 0,
    marginLeft: 13,
  },
  statusBadge: {
    alignSelf: "flex-start",
    borderRadius: 3,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: colors.red,
    marginBottom: 6,
  },
  statusLive: {
    backgroundColor: colors.green,
  },
  statusPending: {
    backgroundColor: "#e0e7e9",
  },
  statusText: {
    color: colors.redText,
    fontSize: 9,
    fontWeight: "900",
  },
  statusTextLive: {
    color: colors.greenText,
  },
  statusTextPending: {
    color: "#566367",
  },
  listingTitle: {
    color: colors.ink,
    fontSize: 16,
    lineHeight: 19,
    fontWeight: "900",
  },
  listingOwner: {
    color: "#5f6c70",
    fontSize: 12,
    marginTop: 2,
  },
  listingNote: {
    color: "#7b6767",
    fontSize: 11,
    fontStyle: "italic",
    marginTop: 3,
  },
  listingNoteLive: {
    color: colors.greenText,
    fontStyle: "normal",
  },
  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    marginTop: 14,
  },
  actionButton: {
    height: 34,
    borderRadius: 7,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  actionDanger: {
    backgroundColor: colors.red,
  },
  actionNeutral: {
    backgroundColor: "#edf1f2",
  },
  actionPrimary: {
    backgroundColor: colors.teal,
  },
  actionText: {
    color: colors.tealDark,
    fontSize: 11,
    fontWeight: "900",
  },
  actionTextDanger: {
    color: colors.redText,
  },
  actionTextPrimary: {
    color: "#fff",
  },
  iconAction: {
    width: 47,
    height: 34,
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
  },
  iconActionPrimary: {
    backgroundColor: colors.teal,
  },
  iconActionNeutral: {
    backgroundColor: "#edf1f2",
  },
  userSearch: {
    marginTop: 2,
    marginBottom: 18,
  },
  reviewPanel: {
    backgroundColor: colors.teal,
    borderRadius: 13,
    padding: 22,
    ...shadow,
  },
  reviewHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  reviewTitle: {
    color: "#fff",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "900",
  },
  pendingPill: {
    height: 24,
    borderRadius: 12,
    paddingHorizontal: 12,
    backgroundColor: colors.green,
    alignItems: "center",
    justifyContent: "center",
  },
  pendingPillText: {
    color: colors.greenText,
    fontSize: 9,
    fontWeight: "900",
  },
  reviewCopy: {
    color: "#96d2d9",
    fontSize: 13,
    lineHeight: 20,
    marginTop: 21,
    marginBottom: 22,
  },
  reviewButton: {
    height: 45,
    borderRadius: 14,
    backgroundColor: "#fff",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  reviewButtonText: {
    color: colors.tealDark,
    fontSize: 13,
    fontWeight: "900",
  },
  userCard: {
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: 18,
    marginBottom: 18,
    ...shadow,
  },
  userHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  userAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.pale,
  },
  userTitleWrap: {
    flex: 1,
    marginLeft: 13,
  },
  userName: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: "900",
  },
  userRoleRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    marginTop: 5,
    gap: 6,
  },
  userRole: {
    color: "#3d4b50",
    fontSize: 9,
    fontWeight: "900",
  },
  userStatusDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
  },
  verifiedDot: {
    backgroundColor: colors.greenText,
  },
  pendingDot: {
    backgroundColor: "#b98200",
  },
  userStatus: {
    fontSize: 9,
    fontWeight: "900",
  },
  verifiedText: {
    color: colors.greenText,
  },
  pendingText: {
    color: "#9a6d00",
  },
  nidRow: {
    minHeight: 53,
    marginTop: 17,
    borderRadius: 18,
    backgroundColor: "#f0f3f4",
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  nidTitle: {
    color: "#526166",
    fontSize: 12,
    fontWeight: "700",
  },
  nidSubtitle: {
    color: "#8a6c18",
    fontSize: 9,
    fontWeight: "900",
    marginTop: 3,
  },
  viewNid: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  viewNidText: {
    color: colors.tealDark,
    fontSize: 11,
    fontWeight: "900",
  },
  userActions: {
    flexDirection: "row",
    gap: 12,
    marginTop: 14,
  },
  rejectButton: {
    flex: 1,
    height: 36,
    borderRadius: 15,
    backgroundColor: colors.red,
    alignItems: "center",
    justifyContent: "center",
  },
  approveButton: {
    flex: 1,
    height: 36,
    borderRadius: 15,
    backgroundColor: colors.green,
    alignItems: "center",
    justifyContent: "center",
  },
  rejectText: {
    color: colors.redText,
    fontSize: 12,
    fontWeight: "900",
  },
  approveText: {
    color: colors.greenText,
    fontSize: 12,
    fontWeight: "900",
  },
  profileButton: {
    height: 36,
    borderRadius: 16,
    backgroundColor: "#e7ecee",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 14,
  },
  profileButtonText: {
    color: "#445157",
    fontSize: 12,
    fontWeight: "900",
  },
  fab: {
    position: "absolute",
    right: 27,
    bottom: 88,
    width: 55,
    height: 55,
    borderRadius: 28,
    backgroundColor: colors.tealDark,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#00363f",
    shadowOpacity: 0.26,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  bottomShell: {
    width: "100%",
    height: 78,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#e4eaed",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    paddingHorizontal: 18,
    ...shadow,
  },
  tabButton: {
    minWidth: 72,
    height: 48,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  tabButtonActive: {
    backgroundColor: colors.teal,
    paddingHorizontal: 13,
  },
  tabLabel: {
    color: "#24363b",
    fontSize: 9,
    fontWeight: "800",
    marginTop: 2,
  },
  tabLabelActive: {
    color: "#fff",
  },
});
